from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping


_TEMPLATE_TOKEN_RE = re.compile(r"\{\{\s*(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\}\}")
_DEFAULT_TEMPLATE_FILENAME = "default_templates.json"


@dataclass(frozen=True, slots=True)
class ProjectTemplate:
    template_id: str
    label: str
    description: str
    files: dict[str, str]
    source_file: str


@dataclass(frozen=True, slots=True)
class ProjectTemplateLoadResult:
    templates: list[ProjectTemplate]
    warnings: list[str]
    template_dir: Path


def _default_project_template_payload() -> dict[str, object]:
    return {
        "version": 1,
        "templates": [
            {
                "id": "python-app",
                "label": "Python Application",
                "description": "src/main.py + pyproject.toml + Python .gitignore",
                "files": {
                    ".gitignore": "__pycache__/\n*.py[cod]\n.venv/\n.tide/\n.pytpo/\n",
                    "README.md": "# {{project_title}}\n\nPython application template generated by PyTPO.\n",
                    "pyproject.toml": (
                        "[project]\n"
                        'name = "{{folder_slug}}"\n'
                        'version = "0.1.0"\n'
                        'description = "{{project_title}}"\n'
                        'readme = "README.md"\n'
                        'requires-python = ">=3.10"\n'
                        "dependencies = []\n"
                    ),
                    "src/main.py": (
                        "def main() -> None:\n"
                        '    print("Hello from {{folder_slug}}")\n\n'
                        'if __name__ == "__main__":\n'
                        "    main()\n"
                    ),
                },
            },
            {
                "id": "python-package",
                "label": "Python Package",
                "description": "src/<package>/ + tests/ + build-ready pyproject.toml",
                "files": {
                    ".gitignore": "__pycache__/\n*.py[cod]\n.venv/\n.pytest_cache/\n.tide/\n.pytpo/\n",
                    "README.md": "# {{project_title}}\n\nPython package template generated by PyTPO.\n",
                    "pyproject.toml": (
                        "[build-system]\n"
                        'requires = ["hatchling"]\n'
                        'build-backend = "hatchling.build"\n\n'
                        "[project]\n"
                        'name = "{{folder_slug}}"\n'
                        'version = "0.1.0"\n'
                        'description = "{{project_title}}"\n'
                        'readme = "README.md"\n'
                        'requires-python = ">=3.10"\n'
                        "dependencies = []\n\n"
                        "[tool.hatch.build.targets.wheel]\n"
                        'packages = ["src/{{module_name}}"]\n'
                    ),
                    "src/{{module_name}}/__init__.py": '__all__ = ["main"]\n__version__ = "0.1.0"\n',
                    "src/{{module_name}}/main.py": (
                        "def main() -> None:\n"
                        '    print("Hello from {{module_name}}")\n\n'
                        'if __name__ == "__main__":\n'
                        "    main()\n"
                    ),
                    "tests/test_smoke.py": (
                        "from {{module_name}}.main import main\n\n\n"
                        "def test_smoke() -> None:\n"
                        "    assert callable(main)\n"
                    ),
                },
            },
            {
                "id": "rust-bin",
                "label": "Rust Binary",
                "description": "Cargo.toml + src/main.rs + Rust .gitignore",
                "files": {
                    ".gitignore": "/target/\n.tide/\n.pytpo/\n",
                    "README.md": "# {{project_title}}\n\nRust binary template generated by PyTPO.\n",
                    "Cargo.toml": (
                        "[package]\n"
                        'name = "{{cargo_name}}"\n'
                        'version = "0.1.0"\n'
                        'edition = "2021"\n\n'
                        "[dependencies]\n"
                    ),
                    "src/main.rs": (
                        "fn main() {\n"
                        '    println!("Hello from {{cargo_name}}!");\n'
                        "}\n"
                    ),
                },
            },
            {
                "id": "cpp-cmake",
                "label": "C++ (CMake)",
                "description": "CMakeLists.txt + src/main.cpp + C/C++ .gitignore",
                "files": {
                    ".gitignore": "/build/\n.tide/\n.pytpo/\n",
                    "README.md": "# {{project_title}}\n\nC++ CMake template generated by PyTPO.\n",
                    "CMakeLists.txt": (
                        "cmake_minimum_required(VERSION 3.16)\n"
                        "project({{cmake_name}} LANGUAGES CXX)\n\n"
                        "set(CMAKE_CXX_STANDARD 17)\n"
                        "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n"
                        "set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n\n"
                        "add_executable({{cmake_name}} src/main.cpp)\n"
                    ),
                    "src/main.cpp": (
                        "#include <iostream>\n\n"
                        "int main() {\n"
                        '    std::cout << "Hello from CMake template!" << std::endl;\n'
                        "    return 0;\n"
                        "}\n"
                    ),
                },
            },
            {
                "id": "tdoc-project",
                "label": "TDOC Project",
                "description": ".tdocproject + starter .tdoc documents + TDOC .gitignore",
                "files": {
                    ".gitignore": ".tide/\n.pytpo/\n",
                    "README.md": (
                        "# {{project_title}}\n\n"
                        "TDOC project template generated by PyTPO.\n\n"
                        "Use `Build TDOC Index` in the IDE toolbar to generate or refresh `index.tdoc`.\n"
                    ),
                    ".tdocproject": (
                        "# TDOC symbol definitions\n"
                        "# Section headers end with ':'\n\n"
                        "Guides:\n"
                        "    Getting Started\n"
                    ),
                    "overview.tdoc": (
                        "---\n"
                        "title: Overview\n"
                        "status: draft\n"
                        "index: on\n"
                        "---\n\n"
                        "# Overview\n\n"
                        "Welcome to your TDOC project.\n\n"
                        "Continue with [Getting Started].\n"
                    ),
                    "guides/getting-started.tdoc": (
                        "---\n"
                        "title: Getting Started\n"
                        "status: draft\n"
                        "index: on\n"
                        "---\n\n"
                        "# Getting Started\n\n"
                        "This document is indexed and linked from [Overview|overview.tdoc].\n\n"
                        "Add more symbols in `.tdocproject` and reference them with [Symbol Name].\n"
                    ),
                },
            },
            {
                "id": "empty",
                "label": "Empty Project",
                "description": "README.md only",
                "files": {
                    "README.md": "# {{project_title}}\n\nProject created with PyTPO.\n",
                },
            },
        ],
    }


def project_template_dir(ide_app_dir: str | Path) -> Path:
    return Path(ide_app_dir).expanduser().resolve() / "templates"


def ensure_bootstrap_project_templates(ide_app_dir: str | Path) -> Path:
    templates_dir = project_template_dir(ide_app_dir)
    templates_dir.mkdir(parents=True, exist_ok=True)
    default_file = templates_dir / _DEFAULT_TEMPLATE_FILENAME
    if default_file.exists():
        return default_file
    payload = _default_project_template_payload()
    default_file.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return default_file


def _coerce_template_entry(raw: object, *, source_file: str) -> tuple[ProjectTemplate | None, str | None]:
    if not isinstance(raw, Mapping):
        return None, "Template entry is not an object."
    template_id = str(raw.get("id") or "").strip()
    label = str(raw.get("label") or "").strip()
    description = str(raw.get("description") or "Project template").strip() or "Project template"
    files_raw = raw.get("files")
    if not template_id:
        return None, "Template is missing a non-empty 'id'."
    if not label:
        return None, f"Template '{template_id}' is missing a non-empty 'label'."
    if not isinstance(files_raw, Mapping):
        return None, f"Template '{template_id}' is missing a 'files' object."
    files: dict[str, str] = {}
    for key_obj, value_obj in files_raw.items():
        key = str(key_obj or "").strip()
        if not key:
            continue
        files[key] = str(value_obj or "")
    if not files:
        return None, f"Template '{template_id}' has no valid file entries."
    return (
        ProjectTemplate(
            template_id=template_id,
            label=label,
            description=description,
            files=files,
            source_file=source_file,
        ),
        None,
    )


def _extract_template_entries(data: object) -> list[object] | None:
    if isinstance(data, list):
        return data
    if isinstance(data, Mapping):
        entries = data.get("templates")
        if isinstance(entries, list):
            return entries
    return None


def _fallback_default_templates() -> list[ProjectTemplate]:
    payload = _default_project_template_payload()
    raw_entries = _extract_template_entries(payload) or []
    out: list[ProjectTemplate] = []
    for raw in raw_entries:
        template, _warning = _coerce_template_entry(raw, source_file=_DEFAULT_TEMPLATE_FILENAME)
        if isinstance(template, ProjectTemplate):
            out.append(template)
    return out


def load_project_templates(ide_app_dir: str | Path) -> ProjectTemplateLoadResult:
    templates_dir = project_template_dir(ide_app_dir)
    bootstrap_file = ensure_bootstrap_project_templates(ide_app_dir)
    warnings: list[str] = []

    templates_by_id: dict[str, ProjectTemplate] = {}
    ordered_ids: list[str] = []

    for path in sorted(templates_dir.glob("*.json"), key=lambda p: p.name.lower()):
        source_name = str(path.name)
        try:
            raw_data = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            warnings.append(f"{source_name}: could not read template file ({exc}).")
            continue

        entries = _extract_template_entries(raw_data)
        if entries is None:
            warnings.append(f"{source_name}: expected a JSON object with 'templates' list or a top-level list.")
            continue
        for raw_entry in entries:
            template, warning = _coerce_template_entry(raw_entry, source_file=source_name)
            if warning:
                warnings.append(f"{source_name}: {warning}")
                continue
            assert template is not None
            tid = template.template_id
            if tid not in templates_by_id:
                ordered_ids.append(tid)
            else:
                prev = templates_by_id[tid]
                warnings.append(
                    f"{source_name}: overriding template '{tid}' previously loaded from {prev.source_file}."
                )
            templates_by_id[tid] = template

    templates = [templates_by_id[tid] for tid in ordered_ids if tid in templates_by_id]
    if not templates:
        templates = _fallback_default_templates()
        warnings.append(
            "No valid project templates were loaded from templates/*.json; using built-in fallback templates."
        )

    if not bootstrap_file.exists():
        warnings.append("Could not create default template bootstrap file.")

    return ProjectTemplateLoadResult(
        templates=templates,
        warnings=warnings,
        template_dir=templates_dir,
    )


def _render_template_tokens(text: str, variables: Mapping[str, str]) -> str:
    source = str(text or "")
    values = {str(k): str(v) for k, v in dict(variables or {}).items()}

    def _replace(match: re.Match[str]) -> str:
        key = str(match.group("name") or "")
        return values.get(key, match.group(0))

    return _TEMPLATE_TOKEN_RE.sub(_replace, source)


def render_project_template_files(template: ProjectTemplate, variables: Mapping[str, str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for raw_path, raw_content in template.files.items():
        path = _render_template_tokens(str(raw_path or ""), variables).strip()
        if not path:
            continue
        out[path] = _render_template_tokens(str(raw_content or ""), variables)
    return out


__all__ = [
    "ProjectTemplate",
    "ProjectTemplateLoadResult",
    "ensure_bootstrap_project_templates",
    "load_project_templates",
    "project_template_dir",
    "render_project_template_files",
]
